name: Your New Jekyll Site
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
repository: 'rendrap/League-Boilerplate'
paginate: 4
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate